Feat/copy link element
devmaslove/unityspace_app pull request #173
Opened 2024-06-06 11:49 UTC by malost73

2024-06-06 12:36 UTC, devmaslove requested changes

2024-06-06 12:36 UTC, devmaslove commented on lib/screens/space_screen/pages/project_content/project_content.dart
> +  Future<void>? hideProjectTabDocs() {
Убрать нуллабл

2024-06-06 12:36 UTC, devmaslove commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +          store: context.wstore<ProjectContentStore>(),
Вместо этой конструкции надо вообще не указывать store и прописывать WStoreBuilder<ProjectContentStore>

2024-06-06 13:06 UTC, devmaslove requested changes

2024-06-06 13:06 UTC, devmaslove commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_tab.dart
> +  final (String, String) tab;
Переделать

2024-06-06 15:40 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/project_content.dart
> +  void hideProjectTabDocs() {
а тут не нужен никакой setStore()? hide как будто бы предполагает изменения на ui

2024-06-06 15:40 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/project_content.dart
> +  void hideProjectTabDocs() {
добавь tryToHide и вынеси туда проверку на null для проекта

2024-06-07 06:20 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/project_content.dart
> +      PopupItemActionTypes.delete => null,
return switch (action) {
      NavbarPopupItemTypes.hide => hideProjectTabDocs(),
      NavbarPopupItemTypes.copyLink => copyTabLink(tabId),
      NavbarPopupItemTypes.edit || NavbarPopupItemTypes.delete => null,
    };
    
    можно чуть покороче

2024-06-07 06:25 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +                      shrinkWrap: true,
это с билдером лучше не использовать, смысл билдера теряется
shrinkWrap заставляет лист посчитать все размеры детей и не дает отрисовать их по надобности

2024-06-07 06:42 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +                            final action = await showOnLongPressMenu(
зачем прокидывать и контекст, и отдельно локализацию?
можно взять локализацию уже внутри

2024-06-07 06:43 UTC, devmaslove requested changes

2024-06-07 06:43 UTC, devmaslove commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +  } else {
Сделай отдельные getListPopMenuDocuments и getListPopMenuEmbed

2024-06-07 06:44 UTC, devmaslove submitted a review, later dismissed

2024-06-07 06:45 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +  required String tabId,
а почему от nullable? если действие null, то и показывать ничего не надо?

2024-06-07 06:48 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +List<PopupMenuItem<PopupItemActionTypes>> getListPopupMenu({
на 2 листа

2024-06-07 06:49 UTC, bukhanovskayamarina22 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_tab.dart
> +  final VoidCallback onPressed;
почему один nullable а второй нет?

2024-06-07 06:51 UTC, bukhanovskayamarina22 commented on lib/screens/widgets/tabs_list/tab_button.dart
>          onTap: selected ? null : onPressed,
при это здесь onTap, который по идее должен быть тем же, что и onPressed, устанавливается в null

2024-06-07 06:54 UTC, malost73 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_switches.dart
> +  required String tabId,
все верно

2024-06-07 06:55 UTC, malost73 commented on lib/screens/space_screen/pages/project_content/widgets/navbar/navbar_tab.dart
> +  final VoidCallback onPressed;
потому что  onPressed обязательный, а onLongPress нет

2024-06-07 07:11 UTC, bukhanovskayamarina22 approved these changes

2024-06-07 07:11 UTC, merged